name: Mobile Android Build + Release

on:
  push:
    branches:
      - shiv
    paths:
      - "Selu383.SP26.Mobile/**"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: Selu383.SP26.Mobile/package-lock.json

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: ğŸ“¦ Install dependencies
        working-directory: Selu383.SP26.Mobile
        run: npm ci

      - name: Sanity check Expo config
        working-directory: Selu383.SP26.Mobile
        run: npx expo config --json

      - name: ğŸš€ Build app
        working-directory: Selu383.SP26.Mobile
        env:
          EAS_LOCAL_BUILD_ARTIFACTS_DIR: ${{ runner.temp }}
          EAS_BUILD_NO_EXPO_GO_WARNING: "true"
        run: eas build -p android --non-interactive

      - name: ğŸ›³ï¸ Make Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
      files: |
        ${{ runner.temp }}/*.apk
        ${{ runner.temp }}/*.aab